name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  retry_count: ${{ github.event.inputs.retry_count }}
  max_retries: 3
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which Revanced do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'All'
          - 'Revanced'
          - 'Revanced Beta'
          - 'ReX'
          - 'Rex-rufusin'
          - 'Rex-anddea'
          - 'Revanced Extended'
          - 'Revanced Extended Android 6,7'
          - 'Revanced Extended Android 5'
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rv:
    name: Patch Revanced
    if: ${{ github.event.inputs.org == 'Revanced' || github.event.inputs.org == 'All' || inputs.org == 'Revanced' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Include:
          - org: "Revanced"
            run: "1"
          - org: "Revanced"
            run: "2"
          - org: "Revanced"
            run: "3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        run: bash src/build/Revanced-${{ matrix.Include.run }}.sh
      - name: Releasing APK files
        if: steps.check-gh-rv.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rv.outcome == 'skipped' && env.retry_count < env.max_retries && matrix.Include.run == '1'
        uses: ./.github/actions/re-run
  patch_rv_beta:
    name: Patch Revanced Beta
    if: ${{ github.event.inputs.org == 'Revanced Beta' || github.event.inputs.org == 'All' || inputs.org == 'Revanced Beta' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rvb
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rvb
        if: steps.check-gh-rvb.outputs.internet_error == '0'
        run: bash src/build/Revanced-Beta.sh
      - name: Releasing APK files
        if: steps.check-gh-rvb.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rvb.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
  patch_rex:
    name: Patch ReX
    if: ${{ github.event.inputs.org == 'ReX' || github.event.inputs.org == 'All' || inputs.org == 'ReX' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rex
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rex
        if: steps.check-gh-rex.outputs.internet_error == '0'
        run: bash src/build/ReX.sh
      - name: Releasing APK files
        if: steps.check-gh-rex.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rex.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
  patch_rex_rufusin:
    name: Patch ReX forked by rufusin
    if: ${{ github.event.inputs.org == 'ReX-rufusin' || github.event.inputs.org == 'All' || inputs.org == 'ReX-rufusin' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rex-rufusin
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rex
        if: steps.check-gh-rex-rufusin.outputs.internet_error == '0'
        run: bash src/build/ReX-rufusin.sh
      - name: Releasing APK files
        if: steps.check-gh-rex-rufusin.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rex-rufusin.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
  patch_rex_anddea:
    name: Patch ReX forked by anddea
    if: ${{ github.event.inputs.org == 'ReX-anddea' || github.event.inputs.org == 'All' || inputs.org == 'ReX-anddea' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rex-anddea
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rex
        if: steps.check-gh-rex-anddea.outputs.internet_error == '0'
        run: bash src/build/ReX-anddea.sh
      - name: Releasing APK files
        if: steps.check-gh-rex-anddea.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rex-anddea.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
  patch_rve:
    name: Patch Revanced Extended
    if: ${{ github.event.inputs.org == 'Revanced Extended' || github.event.inputs.org == 'All' || inputs.org == 'Revanced Extended' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve
        if: steps.check-gh-rve.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended.sh
      - name: Releasing APK files
        if: steps.check-gh-rve.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rve.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
  patch_rve67:
    name: Patch Revanced Extended Android 6,7
    if: ${{ github.event.inputs.org == 'Revanced Extended Android 6,7' || github.event.inputs.org == 'All' || inputs.org == 'Revanced Extended Android 6,7' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve67
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve67
        if: steps.check-gh-rve67.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended-Android-6-7.sh
      - name: Releasing APK files
        if: steps.check-gh-rve67.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rve67.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
  patch_rve5:
    name: Patch Revanced Extended Android 5
    if: ${{ github.event.inputs.org == 'Revanced Extended Android 5' || github.event.inputs.org == 'All' || inputs.org == 'Revanced Extended Android 5' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve5
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve5
        if: steps.check-gh-rve5.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended-Android-5.sh
      - name: Releasing APK files
        if: steps.check-gh-rve5.outputs.internet_error == '0'
        uses: ./.github/actions/release
      - name: Re-run workflow if github connection not stable
        if: always() && steps.patch-rve5.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: ./.github/actions/re-run
