name: 1. Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Revanced'
          - 'Revanced Extended'
          - 'Revanced Extended Arsclib'
          - 'Revanced LisoUseInAIKyrios'
          - 'RVE-anddea-stable'

          - 'Twitter Piko Stable'
      release_tag:
        description: 'Release Tag (Optional)'
        required: false
        type: string

  workflow_call:
    inputs:
      org:
        required: true
        type: string
      release_tag:
        required: false
        type: string
jobs:
  set_tag:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.tag.outputs.release_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          INPUT_TAG="${{ inputs.release_tag || github.event.inputs.release_tag }}"
          ORG="${{ inputs.org || github.event.inputs.org }}"
          echo "Input Tag: $INPUT_TAG"
          echo "Org: $ORG"

          if [[ -n "$INPUT_TAG" ]]; then
            echo "Using provided input tag: $INPUT_TAG"
            echo "release_tag=$INPUT_TAG" >> $GITHUB_OUTPUT
          elif [[ "$ORG" == "All" ]]; then
            NEW_TAG="v$(date +'%Y.%m.%d-%H%M')"
            echo "Org is All, generating new tag: $NEW_TAG"
            echo "release_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          else
            # Try to get latest tag
            LATEST_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "")
            if [[ -n "$LATEST_TAG" ]]; then
              echo "Found latest tag: $LATEST_TAG"
              echo "release_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
            else
              NEW_TAG="v$(date +'%Y.%m.%d-%H%M')"
              echo "No existing releases, generating new tag: $NEW_TAG"
              echo "release_tag=$NEW_TAG" >> $GITHUB_OUTPUT
            fi
          fi

  patch_rv:
    name: Patch Revanced Stable
    if: ${{ github.event.inputs.org == 'Revanced' || inputs.org == 'Revanced' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        run: bash src/build/Revanced.sh ${{ matrix.run }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: revanced-stable-${{ matrix.run }}
          path: ./release/*.apk
          retention-days: 1

      - name: Prepare Artifacts
        if: always()
        run: |
          mv ./release/app_versions.md ./release/app_versions_${{ matrix.run }}.md || true
          mv ./release/tools_versions.md ./release/tools_versions_${{ matrix.run }}.md || true

      - name: Upload App Info
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-info-rv-${{ matrix.run }}
          path: ./release/app_versions_${{ matrix.run }}.md
          retention-days: 1

      - name: Upload Tools Info
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tools-info-rv-${{ matrix.run }}
          path: ./release/tools_versions_${{ matrix.run }}.md
          retention-days: 1

  release_rv:
    name: Release Revanced Stable
    needs: [patch_rv, set_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: revanced-stable-*
          merge-multiple: true
          path: ./release
  
      - name: Download App Info
        uses: actions/download-artifact@v4
        with:
          pattern: app-info-rv-*
          merge-multiple: true
          path: ./release-info/apps

      - name: Download Tools Info
        uses: actions/download-artifact@v4
        with:
          pattern: tools-info-rv-*
          merge-multiple: true
          path: ./release-info/tools

      - name: Create Release Notes
        run: |
          cat ./release-info/apps/*.md > release_notes.md || true
          echo -e "\n\n" >> release_notes.md
          cat ./release-info/tools/*.md | sort -u >> release_notes.md || true

      - name: Releasing APK files
        uses: ./.github/actions/release
        with:
          tag_name: ${{ needs.set_tag.outputs.release_tag }}
          release_notes: release_notes.md
          prerelease: ${{ github.ref_name == 'dev' }}

  patch_rv_liso:
    name: Patch Revanced LisoUseInAIKyrios
    if: ${{ github.event.inputs.org == 'Revanced LisoUseInAIKyrios' || inputs.org == 'Revanced LisoUseInAIKyrios' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv-liso
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv-liso
        if: steps.check-gh-rv-liso.outputs.internet_error == '0'
        run: bash src/build/LisoUseInAIKyrios.sh ${{ matrix.run }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: revanced-liso-${{ matrix.run }}
          path: ./release/*.apk
          retention-days: 1
  
      - name: Prepare Artifacts
        if: always()
        run: |
          mv ./release/app_versions.md ./release/app_versions_${{ matrix.run }}.md || true
          mv ./release/tools_versions.md ./release/tools_versions_${{ matrix.run }}.md || true

      - name: Upload App Info
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-info-liso-${{ matrix.run }}
          path: ./release/app_versions_${{ matrix.run }}.md
          retention-days: 1

      - name: Upload Tools Info
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tools-info-liso-${{ matrix.run }}
          path: ./release/tools_versions_${{ matrix.run }}.md
          retention-days: 1
  


  release_rv_liso:
    name: Release Revanced LisoUseInAIKyrios
    needs: [patch_rv_liso, set_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: revanced-liso-*
          merge-multiple: true
          path: ./release
  
      - name: Download App Info
        uses: actions/download-artifact@v4
        with:
          pattern: app-info-liso-*
          merge-multiple: true
          path: ./release-info/apps

      - name: Download Tools Info
        uses: actions/download-artifact@v4
        with:
          pattern: tools-info-liso-*
          merge-multiple: true
          path: ./release-info/tools

      - name: Create Release Notes
        run: |
          cat ./release-info/apps/*.md > release_notes.md || true
          echo -e "\n\n" >> release_notes.md
          cat ./release-info/tools/*.md | sort -u >> release_notes.md || true

      - name: Releasing APK files
        uses: ./.github/actions/release
        with:
          tag_name: ${{ needs.set_tag.outputs.release_tag }}
          release_notes: release_notes.md
          prerelease: ${{ github.ref_name == 'dev' }}
  patch_rve_anddea_stable:
    name: Patch RVX Anddea Stable
    if: ${{ github.event.inputs.org == 'RVE-anddea-stable' || inputs.org == 'RVE-anddea-stable' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve-anddea-stable
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-anddea
        if: steps.check-gh-rve-anddea-stable.outputs.internet_error == '0'
        run: bash src/build/Anddea-Revanced-Extended.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_anddea_stable
          path: |
            ./release/*.apk
            ./release/app_versions.md
            ./release/tools_versions.md
  release_rve_anddea_stable:
    name: Release RVX Anddea Stable
    needs: [patch_rve_anddea_stable, set_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_anddea_stable
          path: ./release
      - name: Create Release Notes
        run: |
          cat ./release/app_versions.md ./release/tools_versions.md > release_notes.md || true
      - name: Releasing APK files
        uses: ./.github/actions/release
        with:
          tag_name: ${{ needs.set_tag.outputs.release_tag }}
          release_notes: release_notes.md
          prerelease: ${{ github.ref_name == 'dev' }}

  patch_rve:
    name: Patch Revanced Extended Stable
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve
        if: steps.check-gh-rve.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_rve
          path: |
            ./release/*.apk
            ./release/app_versions.md
            ./release/tools_versions.md
  release_rve:
    name: Release Revanced Extended Stable
    needs: [patch_rve, set_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_rve
          path: ./release
      - name: Create Release Notes
        run: |
          cat ./release/app_versions.md ./release/tools_versions.md > release_notes.md || true
      - name: Releasing APK files
        uses: ./.github/actions/release
        with:
          tag_name: ${{ needs.set_tag.outputs.release_tag }}
          release_notes: release_notes.md
          prerelease: ${{ github.ref_name == 'dev' }}

  patch_rve_arsclib:
    name: Patch Revanced Extended Arsclib
    needs: set_tag
    if: ${{ github.event.inputs.org == 'Revanced Extended Arsclib' || inputs.org == 'Revanced Extended Arsclib' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve-arsclib
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-arsclib
        if: steps.check-gh-rve-arsclib.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended-Arsclib.sh
      - name: Release Note
        run: |
             cat ./release/app_versions.md ./release/tools_versions.md > release_notes.md || true
      - name: Releasing APK files
        id: release-rve-arsclib
        if: steps.check-gh-rve-arsclib.outputs.internet_error == '0'
        uses: ./.github/actions/release
        with:
          tag_name: ${{ needs.set_tag.outputs.release_tag }}
          release_notes: release_notes.md
          prerelease: ${{ github.ref_name == 'dev' }}
  patch_twitter_piko_stable:
    name: Patch Twitter Piko Stable
    needs: set_tag
    if: ${{ github.event.inputs.org == 'Twitter Piko Stable' || inputs.org == 'Twitter Piko Stable' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-piko-stable
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        run: bash src/build/Piko.sh
      - name: Release Note
        run: |
             cat ./release/app_versions.md ./release/tools_versions.md > release_notes.md || true
      - name: Releasing APK files
        id: release-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        uses: ./.github/actions/release
        with:
          tag_name: ${{ needs.set_tag.outputs.release_tag }}
          release_notes: release_notes.md
          prerelease: ${{ github.ref_name == 'dev' }}


