name: 1. Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced'
          - 'All'
          - 'Revanced Extended'
          - 'Revanced Extended Arsclib'
          - 'Revanced LisoUseInAIKyrios'
          - 'RVE-anddea-stable'
          - 'Twitter Piko Stable'
          - 'Revanced Experiments'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rv:
    name: Patch Revanced Stable
    if: ${{ github.event.inputs.org == 'Revanced' || inputs.org == 'Revanced' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        run: bash src/build/Revanced.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_rv_liso:
    name: Patch Revanced LisoUseInAIKyrios
    if: ${{ github.event.inputs.org == 'Revanced LisoUseInAIKyrios' || inputs.org == 'Revanced LisoUseInAIKyrios' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv-liso
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv-liso
        if: steps.check-gh-rv-liso.outputs.internet_error == '0'
        run: bash src/build/LisoUseInAIKyrios.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-rv-liso
        if: steps.check-gh-rv-liso.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_rve_anddea_stable:
    name: Patch RVX Anddea Stable
    if: ${{ github.event.inputs.org == 'RVE-anddea-stable' || inputs.org == 'RVE-anddea-stable' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve-anddea-stable
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-anddea
        if: steps.check-gh-rve-anddea-stable.outputs.internet_error == '0'
        run: bash src/build/Anddea-Revanced-Extended.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_anddea_stable
          path: |
            ./release/*.apk
  release_rve_anddea_stable:
    name: Release RVX Anddea Stable
    needs: patch_rve_anddea_stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_anddea_stable
          path: ./release
      - name: Releasing APK files
        uses: ./.github/actions/release

  patch_rve:
    name: Patch Revanced Extended Stable
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve
        if: steps.check-gh-rve.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_rve
          path: |
            ./release/*.apk
  release_rve:
    name: Release Revanced Extended Stable
    needs: patch_rve
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_rve
          path: ./release
      - name: Releasing APK files
        uses: ./.github/actions/release

  patch_rve_arsclib:
    name: Patch Revanced Extended Arsclib
    if: ${{ github.event.inputs.org == 'Revanced Extended Arsclib' || inputs.org == 'Revanced Extended Arsclib' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve-arsclib
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-arsclib
        if: steps.check-gh-rve-arsclib.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended-Arsclib.sh
      - name: Releasing APK files
        id: release-rve-arsclib
        if: steps.check-gh-rve-arsclib.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_twitter_piko_stable:
    name: Patch Twitter Piko Stable
    if: ${{ github.event.inputs.org == 'Twitter Piko Stable' || inputs.org == 'Twitter Piko Stable' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-piko-stable
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        run: bash src/build/Piko.sh
      - name: Releasing APK files
        id: release-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        uses: ./.github/actions/release


  patch_rv_experiments:
    name: Patch Revanced Experiments
    if: ${{ github.event.inputs.org == 'Revanced Experiments' || inputs.org == 'Revanced Experiments' || github.event.inputs.org == 'All' || inputs.org == 'All' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv-experiments
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv-experiments
        if: steps.check-gh-rv-experiments.outputs.internet_error == '0'
        run: bash src/build/Revanced-Experiment.sh
      - name: Releasing APK files
        id: release-rv-experiments
        if: steps.check-gh-rv-experiments.outputs.internet_error == '0'
        uses: ./.github/actions/release
